name: Terraform Infrastructure CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.13.3

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: |
          cd terraform-infrastructure-automation
          terraform init -input=false

      - name: Terraform fmt & validate
        run: |
          cd terraform-infrastructure-automation
          terraform fmt -recursive
          terraform validate

      - name: Minimal tfsec scan
        run: |
          cd terraform-infrastructure-automation
          tfsec . --exclude-check aws-s3-encryption-customer-key,aws-dynamodb-enable-at-rest-encryption \
            || echo "tfsec issues ignored for PoC"

      - name: Terraform plan
        run: |
          cd terraform-infrastructure-automation
          terraform plan -no-color -out=tfplan

          
      - name: Terraform apply
        run: |
          cd terraform-infrastructure-automation
          terraform apply -auto-approve tfplan
