name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-infrastructure-automation/**'
    
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-infrastructure-automation/**'
      

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.13.3

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-infrastructure-automation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec security scan
        run: |
          tfsec . || echo "tfsec found issues but continuing..."
          tfsec --format junit --out tfsec-report.xml . || true
        continue-on-error: true

         


      - name: Upload tfsec report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: tfsec-report.xml


      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: terraform-infrastructure-automation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Save Terraform plan
        if: always()
        run: terraform plan -out=plan.tfplan -input=false


      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
           name: terraform-plan
           path: plan.tfplan


      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfsec-report
          path: ./tfsec-report

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
