name: Terraform Infrastructure CI/CD

on:
  push:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.13.3

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-infrastructure-automation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt & validate
        run: |
          terraform fmt -recursive
          terraform validate

      - name: Install tfsec
        run: curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec security scan
        run: |
          tfsec . || echo "tfsec found issues—continuing"
          tfsec --format junit --out tfsec-report.xml . || true
        continue-on-error: true

      - name: Upload tfsec report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: tfsec-report.xml

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -no-color -out=tfplan -input=false

      - name: Upload terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-infrastructure-automation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAC }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download tfsec report
        uses: actions/download-artifact@v4
        with:
          name: tfsec-report
          path: .

      - name: Download terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
